version: '3.8'

volumes:
  postgres-data:

networks:
  default:
    name: dev-container-test-env-network

services:
  dev-container-test-env:
    container_name: dev-container-test-env-
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_HOSTNAME: postgresdb
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  db:
    container_name: dev-container-test-env-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres